version: '3.8'
services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zarco