services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: zarco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
