server:
  port: ${PORT:8080}
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /
spring:
  application:
    name: zarco-application
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}