datasource:
  read-only:
    url: jdbc:postgresql://localhost:5432/zarco?currentSchema=public
    username: postgres
    password: postgres
  read-write:
    url: jdbc:postgresql://localhost:5432/zarco?currentSchema=public
    username: postgres
    password: postgres

aws:
  sqs:
    new-station-queue-url: http://localhost:4566/000000000000/zarco-new-station