server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /zarco-api

management:
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs
  writer-with-order-by-keys: true
  use-fqn: true
#  group-configs:
#    - group: v1
#      display-name: Version 1
#      paths-to-match:
#        - /v1/**
#    - group: v2
#      display-name: Version 2
#      paths-to-match:
#        - /v2/**

spring:
  main:
    banner-mode: off
  application:
    name: zarco-service
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: 123
      sqs:
        endpoint: http://localhost:4566
        region: us-east-1

datasource:
  read-write:
    url: ${READ_WRITE_DATASOURCE_URL}
    username: ${READ_WRITE_DATASOURCE_USERNAME}
    password: ${READ_WRITE_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  read-only:
    url: ${READ_ONLY_DATASOURCE_URL}
    username: ${READ_ONLY_DATASOURCE_USERNAME}
    password: ${READ_ONLY_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      read-only: true

aws:
  sqs:
    new-station-queue-url: ${AWS_SQS_NEW_STATION_QUEUE_URL}