server:
  port: ${PORT:8080}
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /
spring:
  main:
    banner-mode: off
  application:
    name: zarco-application
  datasource:
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/zarco}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:migrations/changelog.yml