name: CD
on:
  release:
    types: [released]
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Clean port 80
        run: sudo kill -9 `sudo lsof -t -i:80`
      - name: Run app
        run: sudo java -jar /home/ubuntu/actions-runner/_work/zarco.info/zarco.info/target/zarco-0.0.1-SNAPSHOT.jar &